### PR TITLE
Update _isWithinConfigurationExperience function

### PR DESCRIPTION
**Pull request by Csmith246**
@rslibed @kellyhutchins Is this the proper logic that we want in here for the `_isWithinConfigurationExperience` function?

### CODE REVIEW

**Review by kellyhutchins — APPROVED** [review]
Looks good... we can update one app and test all these scenarios once its checked in

**Review by rslibed — APPROVED** [review]

**Comment by Csmith246** [comment]
@kellyhutchins I had an old version of this function. I took this new version from a template app, so I assume that it already works correctly for the template apps. @rslibed Can you confirm that?

**Comment by rslibed** [comment]
Yes, the `withinConfigurationExperience` method looks good

**Comment by Csmith246** [comment]
Great, thanks. @kellyhutchins I incremented the package version number to 0.0.4. Could you publish when you get the chance?

**Pull request merged**
