### PR TITLE
add some reporter config options

### PR DESCRIPTION
**Pull request by jmhauck**

### CODE REVIEW

**Comment by jmhauck** [comment]
@kellyhutchins when a string default value is provided in these config files...do we have some mechanism for that value to be translated?

**Comment by kellyhutchins** [comment]
@jmhauck  in the config json no but you can in the templates configuration where you setup the props. Although I think it makes the most sense to do so in the app. @rslibed for the language switcher where does it make the most sense for these props to be?

We'll probably need them to be english only for this release

**Comment by rslibed** [comment]
> @jmhauck in the config json no but you can in the templates configuration where you setup the props. Although I think it makes the most sense to do so in the app. @rslibed for the language switcher where does it make the most sense for these props to be?
> 
> We'll probably need them to be english only for this release

Let's set the `defaultValue` prop (hardcode in `en`) for each of these in the app's respective preset config settings file in the configure template repo. From there, the language translator modal will pick these up from there when the app gets the language switcher. 

Example: 
```
     reportsHeader: {
        type: "string",
        stringType: "title",
        label: reportsHeader.label,
        // HARDCODED IN EN
        defaultValue: "Reports",
        searchTerms: [searchTerms.title]
      }
```

**Comment by jmhauck** [comment]
@rslibed @kellyhutchins cool to merge now that those strings are pulled?

**Review by rslibed — APPROVED** [review]

**Pull request merged**
