### PR TITLE
minor suggestions

### PR DESCRIPTION
**Pull request by jmhauck**

### CODE REVIEW

**Comment by kellyhutchins** [comment]
@jmhauck  can you tell me more about these suggestions? Looks like the loop through the sources is removed?

**Comment by jmhauck** [comment]
@kellyhutchins it was a redundant set of loops though the sources. Still have one pass through the sources but it checks both source types. Won't have all that many sources so two passes vs one won't change much.

**Comment by kellyhutchins** [comment]
@jmhauck  ah got it - makes much more sense this morning instead of late last night :) I'm going to approve this one but let's hold off on merging until post-release/patch. We'll want to test it in all the apps just to verify that everything is ok

**Review by kellyhutchins — APPROVED** [review]

**Comment by Csmith246** [comment]
@jmhauck @kellyhutchins - just saw this in the PR queue. Do you guys think this is good to merge now?

**Comment by kellyhutchins** [comment]
Looks like this one was resolved

**Pull request closed without merging**
